//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 07:42:01 PM NST 
//


package ca.phon.query.scripttable.io;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.phon.engines.scripttable.io package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Table_QNAME = new QName("http://phon.ling.mun.ca/ns/scripttable", "table");
    private final static QName _Column_QNAME = new QName("http://phon.ling.mun.ca/ns/scripttable", "column");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.phon.engines.scripttable.io
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScriptParam }
     * 
     */
    public ScriptParam createScriptParam() {
        return new ScriptParam();
    }

    /**
     * Create an instance of {@link ScriptTable }
     * 
     */
    public ScriptTable createScriptTable() {
        return new ScriptTable();
    }

    /**
     * Create an instance of {@link ScriptTableColumn }
     * 
     */
    public ScriptTableColumn createScriptTableColumn() {
        return new ScriptTableColumn();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScriptTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/scripttable", name = "table")
    public JAXBElement<ScriptTable> createTable(ScriptTable value) {
        return new JAXBElement<ScriptTable>(_Table_QNAME, ScriptTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScriptTableColumn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/scripttable", name = "column")
    public JAXBElement<ScriptTableColumn> createColumn(ScriptTableColumn value) {
        return new JAXBElement<ScriptTableColumn>(_Column_QNAME, ScriptTableColumn.class, null, value);
    }

}
