//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 07:42:01 PM NST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://phon.ling.mun.ca/ns/scripttable")
package ca.phon.query.scripttable.io;
