/*
 * Phon - An open source tool for research in phonology.
 * Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 09:38:54 AM NST 
//


package ca.phon.query.report.design;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.phon.engines.search.report.design package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReportSection_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "report-section");
    private final static QName _Value_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "value");
    private final static QName _ResultListing_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "result-listing");
    private final static QName _AggregateInventory_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "aggregateInventory");
    private final static QName _ParamName_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "paramName");
    private final static QName _Comment_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "comment");
    private final static QName _Group_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "group");
    private final static QName _Field_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "field");
    private final static QName _FieldValue_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "field-value");
    private final static QName _Inventory_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "inventory");
    private final static QName _TierName_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "tierName");
    private final static QName _Format_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "format");
    private final static QName _Params_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "params");
    private final static QName _GroupReportSection_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "group-report-section");
    private final static QName _Expr_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "expr");
    private final static QName _Metakey_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "metakey");
    private final static QName _ReportDesign_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "report-design");
    private final static QName _Summary_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "summary");
    private final static QName _GroupComment_QNAME = new QName("http://phon.ling.mun.ca/ns/report", "group-comment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.phon.engines.search.report.design
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link CommentSection }
     * 
     */
    public CommentSection createCommentSection() {
        return new CommentSection();
    }

    /**
     * Create an instance of {@link AggregrateInventory }
     * 
     */
    public AggregrateInventory createAggregrateInventory() {
        return new AggregrateInventory();
    }

    /**
     * Create an instance of {@link ScriptContainer }
     * 
     */
    public ScriptContainer createScriptContainer() {
        return new ScriptContainer();
    }

    /**
     * Create an instance of {@link InventorySection }
     * 
     */
    public InventorySection createInventorySection() {
        return new InventorySection();
    }

    /**
     * Create an instance of {@link ResultListing }
     * 
     */
    public ResultListing createResultListing() {
        return new ResultListing();
    }

    /**
     * Create an instance of {@link ParamSection }
     * 
     */
    public ParamSection createParamSection() {
        return new ParamSection();
    }

    /**
     * Create an instance of {@link SummarySection }
     * 
     */
    public SummarySection createSummarySection() {
        return new SummarySection();
    }

    /**
     * Create an instance of {@link ReportDesign }
     * 
     */
    public ReportDesign createReportDesign() {
        return new ReportDesign();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ScriptParameter }
     * 
     */
    public ScriptParameter createScriptParameter() {
        return new ScriptParameter();
    }

    /**
     * Create an instance of {@link ResultListingField }
     * 
     */
    public ResultListingField createResultListingField() {
        return new ResultListingField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Section }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "report-section")
    public JAXBElement<Section> createReportSection(Section value) {
        return new JAXBElement<Section>(_ReportSection_QNAME, Section.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultListing }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "result-listing", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "group-report-section")
    public JAXBElement<ResultListing> createResultListing(ResultListing value) {
        return new JAXBElement<ResultListing>(_ResultListing_QNAME, ResultListing.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregrateInventory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "aggregateInventory", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "report-section")
    public JAXBElement<AggregrateInventory> createAggregateInventory(AggregrateInventory value) {
        return new JAXBElement<AggregrateInventory>(_AggregateInventory_QNAME, AggregrateInventory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "paramName")
    public JAXBElement<String> createParamName(String value) {
        return new JAXBElement<String>(_ParamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "comment", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "report-section")
    public JAXBElement<CommentSection> createComment(CommentSection value) {
        return new JAXBElement<CommentSection>(_Comment_QNAME, CommentSection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "group", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "report-section")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultListingField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "field")
    public JAXBElement<ResultListingField> createField(ResultListingField value) {
        return new JAXBElement<ResultListingField>(_Field_QNAME, ResultListingField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScriptContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "field-value")
    public JAXBElement<ScriptContainer> createFieldValue(ScriptContainer value) {
        return new JAXBElement<ScriptContainer>(_FieldValue_QNAME, ScriptContainer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InventorySection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "inventory", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "group-report-section")
    public JAXBElement<InventorySection> createInventory(InventorySection value) {
        return new JAXBElement<InventorySection>(_Inventory_QNAME, InventorySection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "tierName")
    public JAXBElement<String> createTierName(String value) {
        return new JAXBElement<String>(_TierName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "format")
    public JAXBElement<String> createFormat(String value) {
        return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParamSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "params", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "report-section")
    public JAXBElement<ParamSection> createParams(ParamSection value) {
        return new JAXBElement<ParamSection>(_Params_QNAME, ParamSection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Section }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "group-report-section")
    public JAXBElement<Section> createGroupReportSection(Section value) {
        return new JAXBElement<Section>(_GroupReportSection_QNAME, Section.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "expr")
    public JAXBElement<String> createExpr(String value) {
        return new JAXBElement<String>(_Expr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "metakey")
    public JAXBElement<String> createMetakey(String value) {
        return new JAXBElement<String>(_Metakey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportDesign }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "report-design")
    public JAXBElement<ReportDesign> createReportDesign(ReportDesign value) {
        return new JAXBElement<ReportDesign>(_ReportDesign_QNAME, ReportDesign.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummarySection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "summary", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "report-section")
    public JAXBElement<SummarySection> createSummary(SummarySection value) {
        return new JAXBElement<SummarySection>(_Summary_QNAME, SummarySection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://phon.ling.mun.ca/ns/report", name = "group-comment", substitutionHeadNamespace = "http://phon.ling.mun.ca/ns/report", substitutionHeadName = "group-report-section")
    public JAXBElement<CommentSection> createGroupComment(CommentSection value) {
        return new JAXBElement<CommentSection>(_GroupComment_QNAME, CommentSection.class, null, value);
    }

}
