/*
 * Phon - An open source tool for research in phonology.
 * Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 09:38:54 AM NST 
//


package ca.phon.query.report.design;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Report settings.
 * 
 * <p>Java class for reportDesign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reportDesign">
 *   &lt;complexContent>
 *     &lt;extension base="{http://phon.ling.mun.ca/ns/report}section">
 *       &lt;sequence>
 *         &lt;element ref="{http://phon.ling.mun.ca/ns/report}report-section" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportDesign", propOrder = {
    "reportSection"
})
public class ReportDesign
    extends Section
{

    @XmlElementRef(name = "report-section", namespace = "http://phon.ling.mun.ca/ns/report", type = JAXBElement.class)
    protected List<JAXBElement<? extends Section>> reportSection;

    /**
     * Gets the value of the reportSection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportSection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SummarySection }{@code >}
     * {@link JAXBElement }{@code <}{@link Section }{@code >}
     * {@link JAXBElement }{@code <}{@link CommentSection }{@code >}
     * {@link JAXBElement }{@code <}{@link Group }{@code >}
     * {@link JAXBElement }{@code <}{@link AggregrateInventory }{@code >}
     * {@link JAXBElement }{@code <}{@link ParamSection }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Section>> getReportSection() {
        if (reportSection == null) {
            reportSection = new ArrayList<JAXBElement<? extends Section>>();
        }
        return this.reportSection;
    }

}
