/*
 * Phon - An open source tool for research in phonology.
 * Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 09:38:54 AM NST 
//


package ca.phon.query.report.design;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resultListing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resultListing">
 *   &lt;complexContent>
 *     &lt;extension base="{http://phon.ling.mun.ca/ns/report}section">
 *       &lt;sequence>
 *         &lt;element ref="{http://phon.ling.mun.ca/ns/report}field" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="format" type="{http://phon.ling.mun.ca/ns/report}resultListingFormatType" default="table" />
 *       &lt;attribute name="includeExcluded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultListing", propOrder = {
    "field"
})
public class ResultListing
    extends Section
{

    @XmlElement(required = true)
    protected List<ResultListingField> field;
    @XmlAttribute
    protected ResultListingFormatType format;
    @XmlAttribute
    protected Boolean includeExcluded;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultListingField }
     * 
     * 
     */
    public List<ResultListingField> getField() {
        if (field == null) {
            field = new ArrayList<ResultListingField>();
        }
        return this.field;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link ResultListingFormatType }
     *     
     */
    public ResultListingFormatType getFormat() {
        if (format == null) {
            return ResultListingFormatType.TABLE;
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultListingFormatType }
     *     
     */
    public void setFormat(ResultListingFormatType value) {
        this.format = value;
    }

    /**
     * Gets the value of the includeExcluded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIncludeExcluded() {
        if (includeExcluded == null) {
            return false;
        } else {
            return includeExcluded;
        }
    }

    /**
     * Sets the value of the includeExcluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeExcluded(Boolean value) {
        this.includeExcluded = value;
    }

}
